---
- hosts: all
  become: yes
  tasks:
  - name: i want to install webserver on ansible ubuntu nodes
    apt:
      name: apache2
      state: present     
    when: ansible_os_family =="Debian"

  - name: i want to start webserver on ansible ubuntu nodes
    service:
      name: apache2
      state: started
    when: ansible_os_family =="Debian"   

  - name: i want to install webserver on ansible RedHate nodes
    yum: 
      name: httpd
      state: present
    when: ansible_os_family =="RedHate"

  - name: i want to start webserver on ansible RedHate nodes
    service:
        name: httpd
        state: started
    when: ansible_os_family =="RedHate" 
    
           
  


